# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\b220256\Desktop\Kiosk\SetProductWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(300, 200)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 261, 79))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setMaximumSize(QtCore.QSize(60, 30))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setMaximumSize(QtCore.QSize(60, 30))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setMaximumSize(QtCore.QSize(60, 30))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.nameEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.nameEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.nameEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.nameEdit.setObjectName("nameEdit")
        self.gridLayout.addWidget(self.nameEdit, 1, 1, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.imagePathEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.imagePathEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.imagePathEdit.setStyleSheet("QLineEdit{\n"
"    background:rgb(235,235,235);\n"
"}")
        self.imagePathEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.imagePathEdit.setReadOnly(True)
        self.imagePathEdit.setObjectName("imagePathEdit")
        self.horizontalLayout_5.addWidget(self.imagePathEdit)
        self.findButton = QtWidgets.QPushButton(self.layoutWidget)
        self.findButton.setMaximumSize(QtCore.QSize(60, 30))
        self.findButton.setObjectName("findButton")
        self.horizontalLayout_5.addWidget(self.findButton)
        self.gridLayout.addLayout(self.horizontalLayout_5, 0, 1, 1, 1)
        self.priceSpinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.priceSpinBox.setMaximumSize(QtCore.QSize(16777215, 30))
        self.priceSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.priceSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.priceSpinBox.setMinimum(0)
        self.priceSpinBox.setMaximum(1000000)
        self.priceSpinBox.setObjectName("priceSpinBox")
        self.gridLayout.addWidget(self.priceSpinBox, 3, 1, 1, 1)
        self.layoutWidget_2 = QtWidgets.QWidget(Form)
        self.layoutWidget_2.setGeometry(QtCore.QRect(110, 160, 194, 25))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.okayButton = QtWidgets.QPushButton(self.layoutWidget_2)
        self.okayButton.setMaximumSize(QtCore.QSize(70, 25))
        self.okayButton.setObjectName("okayButton")
        self.horizontalLayout.addWidget(self.okayButton)
        self.cancelButton = QtWidgets.QPushButton(self.layoutWidget_2)
        self.cancelButton.setMaximumSize(QtCore.QSize(70, 25))
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "Price"))
        self.label.setText(_translate("Form", "Image"))
        self.label_2.setText(_translate("Form", "Name"))
        self.findButton.setText(_translate("Form", "find"))
        self.priceSpinBox.setSuffix(_translate("Form", "￦"))
        self.okayButton.setText(_translate("Form", "ok"))
        self.cancelButton.setText(_translate("Form", "cancel"))
